<?php
namespace App\ModelView;
require_once "ShortBookModelView.php";
use App\Domain\Author;

class FullBookModelView extends ShortBookModelView
{

    /**
     * @var string[]
     */
    public array $bookContent;
    public string $aboutAuthor;

    public  function setAuthor(Author $author)
    {
        parent::setAuthor($author); // TODO: Change the autogenerated stub
        $this->aboutAuthor = $author->getDescription();
    }

}