<?php
namespace App\ModelView;
require_once "ProfileBookModelView.php";
use App\Domain\Author;
use App\Domain\Book;

class ShortBookModelView extends ProfileBookModelView
{
    public string $bookTitle;
    public string $bookDesc;
    public string $authorName;
    public string $authorId;

    public function setBook(Book $book)
    {
        parent::setBook($book); // TODO: Change the autogenerated stub
        $this->bookTitle = $book->getTitle();
        $this->bookDesc = $book->getDescription();
    }

    public function setAuthor(?Author $author)
    {
        $this->authorName = $author->getFullName();
        $this->authorId =  $author->getId();
    }
}